version: '3.7'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    restart: always
    volumes:
      - ./schemas:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "oauth_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"